### ISSUE TITLE
morphoSimilarity(String sentence1, String sentence2)方法抛出exception

### ISSUE THREAD

**Issue by htx631627464** [shibing624/similarity#45]
java.lang.NoSuchMethodError: com.hankcs.hanlp.corpus.tag.Nature.name()Ljava/lang/String;

	at org.xm.tokenizer.Tokenizer.lambda$segment$0(Tokenizer.java:50)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.xm.tokenizer.Tokenizer.segment(Tokenizer.java:51)
	at org.xm.similarity.sentence.morphology.MorphoSimilarity.segment(MorphoSimilarity.java:131)
	at org.xm.similarity.sentence.morphology.MorphoSimilarity.getSimilarity(MorphoSimilarity.java:55)
	at org.xm.Similarity.morphoSimilarity(Similarity.java:125)

**Comment by shibing624** [comment]
<dependency>
            <groupId>com.hankcs</groupId>
            <artifactId>hanlp</artifactId>
            <version>portable-1.3.4</version>
        </dependency>

**Comment by SlashWong** [comment]
1.3.4版本可以解决。可以close 了
