### ISSUE TITLE
人名识别有问题啊

### ISSUE THREAD

**Issue by jz3707** [shibing624/similarity#8]
Exception in thread "main" java.lang.StackOverflowError
	at java.util.LinkedList.node(LinkedList.java:569)
	at java.util.LinkedList$ListItr.<init>(LinkedList.java:879)
	at java.util.LinkedList.listIterator(LinkedList.java:868)
	at java.util.AbstractList.listIterator(AbstractList.java:299)
	at java.util.AbstractSequentialList.iterator(AbstractSequentialList.java:239)
	at org.xm.similarity.word.hownet.concept.ConceptSimilarity.autoCombineConcepts(ConceptSimilarity.java:131)
	at org.xm.similarity.word.hownet.concept.ConceptSimilarity.getConcepts(ConceptSimilarity.java:103)
	at org.xm.similarity.word.hownet.concept.ConceptSimilarity.autoCombineConcepts(ConceptSimilarity.java:132)
	at org.xm.similarity.word.hownet.concept.ConceptSimilarity.getConcepts(ConceptSimilarity.java:103)
	at org.xm.similarity.word.hownet.concept.ConceptSimilarity.autoCombineConcepts(ConceptSimilarity.java:132)

**Comment by shibing624** [comment]
可以贴出出错的输入文本吗？方便复现该问题。另请简述该问题出现环境。

**Comment by shibing624** [comment]
已经处理。
